import { ExportData, isSafeValid, formatSafeYears } from "./calculations";

const fmtCurrency = (val: number) => {
  if (val >= 1_000_000) return `€${(val / 1_000_000).toFixed(1)}M`;
  if (val >= 1_000) return `€${(val / 1_000).toFixed(0)}K`;
  return `€${val.toFixed(0)}`;
};

export function generateExportText(data: ExportData): string {
  const k = data.kpis;
  const marginStr = isSafeValid(k.ebitdaMargin) ? `${k.ebitdaMargin.value!.toFixed(0)}%` : "N/A";
  const roiStr = isSafeValid(k.roi) ? `${k.roi.value!.toFixed(1)}%` : "N/A";
  const paybackStr = formatSafeYears(k.paybackYears);
  const beStr = isSafeValid(k.breakEvenOccupancy) ? `${k.breakEvenOccupancy.value!.toFixed(0)}%` : "N/A";

  const lines = [
    `═══════════════════════════════════════════`,
    `  INVESTMENT SUMMARY`,
    `  ${data.projectName}`,
    `═══════════════════════════════════════════`,
    ``,
    `Project:     ${data.projectName}`,
    `Location:    ${data.location}`,
    `Version:     ${data.versionName}`,
    `Scenario:    ${data.scenario.charAt(0).toUpperCase() + data.scenario.slice(1)}`,
    `Date:        ${data.date}`,
    ``,
    `───────────────────────────────────────────`,
    `  KEY METRICS`,
    `───────────────────────────────────────────`,
    ``,
    `  Annual Revenue:      ${fmtCurrency(k.totalRevenueYear)}`,
    `  Annual EBITDA:       ${fmtCurrency(k.ebitdaYear)}`,
    `  EBITDA Margin:       ${marginStr}`,
    `  ROI:                 ${roiStr}`,
    `  Payback Period:      ${paybackStr}`,
    `  Break-even Occ.:     ${beStr}`,
    `  Current Occupancy:   ${k.weightedOccupancy.toFixed(0)}%`,
    ``,
    `───────────────────────────────────────────`,
    `  INVESTMENT VERDICT: ${data.verdict.label.toUpperCase()}`,
    `───────────────────────────────────────────`,
    ``,
    `  ${data.verdict.explanation}`,
    ``,
    `  Model Confidence:    ${data.confidence.level.toUpperCase()} (${data.confidence.score}%)`,
    ...(data.confidence.reasons.length > 0 ? [`  Notes: ${data.confidence.reasons.join("; ")}`] : []),
    ``,
    `───────────────────────────────────────────`,
    `  KEY DRIVERS (by EBITDA impact)`,
    `───────────────────────────────────────────`,
    ``,
    ...data.sensitivity.map((s, i) =>
      `  ${i + 1}. ${s.label.padEnd(25)} €${s.ebitdaImpact >= 1000 ? `${(s.ebitdaImpact / 1000).toFixed(0)}K` : s.ebitdaImpact.toFixed(0)}`
    ),
    ``,
    `───────────────────────────────────────────`,
    `  INSIGHT`,
    `───────────────────────────────────────────`,
    ``,
    `  ${data.insight}`,
    ``,
    `───────────────────────────────────────────`,
    `  MODEL INPUTS`,
    `───────────────────────────────────────────`,
    ``,
    `  Courts:              ${data.inputs.numberOfCourts} (${data.inputs.courtType})`,
    `  Hours/Day:           ${data.inputs.openingHoursPerDay}`,
    `  Peak Price:          €${data.inputs.peakPrice}/hr`,
    `  Off-Peak Price:      €${data.inputs.offPeakPrice}/hr`,
    `  Peak Occupancy:      ${data.inputs.peakOccupancy}%`,
    `  Off-Peak Occupancy:  ${data.inputs.offPeakOccupancy}%`,
    `  Investment:          ${fmtCurrency(data.inputs.initialInvestment)}`,
    `  Monthly Costs:       ${fmtCurrency(k.costBreakdown.totalCosts)}`,
    `  Cost Mode:           ${data.inputs.costMode}`,
    ``,
    `═══════════════════════════════════════════`,
    `  Generated by CourtPlan Pro`,
    `═══════════════════════════════════════════`,
  ];

  return lines.join("\n");
}

export function downloadExport(data: ExportData) {
  const text = generateExportText(data);
  const blob = new Blob([text], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${data.projectName.replace(/\s+/g, "_")}_${data.scenario}_summary.txt`;
  a.click();
  URL.revokeObjectURL(url);
}
